label: "label1"
cleaning_functions:
  - name: drop_columns
    args:
      cols:
        - id
        - RUL
        - label2
model:
  - name: StandardScaler
  - name: LogisticRegression
evaluate: "classification"