label: "RUL"
cleaning_functions:
  - name: drop_columns
    args:
      cols:
        - id
        - label1
        - label2
model:
  - name: StandardScaler
  - name: LinearRegression
evaluate: regression
