label: "RUL"
cleaning_functions:
  - name: drop_columns
    args:
      cols:
        - id
        - label1
        - label2
feature_functions:
  - name: standard_scaler
evaluate: regression
model: LinearRegression
